version: '2'

services:
  rap3:
    build: ./RAP3
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ~/scripts:/var/html/www/RAP3/scripts

  db:
    build: ./RAP3DB
    volumes:
      - ~/database:/var/lib/mysql

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db

