version: '3.7'

volumes:
  db-data:

networks:
  db:

services:
  prototype:
    container_name: prototype
    build:
      context: .
      args:
        - AMPERSAND_SCRIPT=ProjectAdministration.adl
        - AMPERSAND_DB_HOST=prototype-db
    volumes:
      - ./:/src
    restart: always
    depends_on:
      - prototype-db
    ports:
      - "80:80"
    networks:
      - db
  
  prototype-db:
    restart: always
    image: ampersand-prototype-db
    volumes:
      - db-data:/var/lib/mysql
    container_name: prototype-db
    build:
      context: prototype-db
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - prototype-db
    ports:
      - "8080:80"
    networks:
      - db
    environment:
      - PMA_HOST=prototype-db # https://hub.docker.com/r/phpmyadmin/phpmyadmin/