version: '2'

services:
  rap3:
    restart: always
    build: ./RAP3
    ports:
      - "80:80"
    links:
      - db
    environment:
    - AMPERSAND_DB_HOST="db"
 
  db:
    restart: always
    build: ./RAP3DB

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db
