version: '2'

services:
  rap3:
    build: ./RAP3
    ports:
      - "80:80"
    links:
      - db

  db:
    build: ./RAP3DB

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db

