version: '2'

services:
  rap3:
    build: ./RAP3
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - /home/ampersandadmin/scripts:/var/html/www/RAP3/scripts
 
  db:
    build: ./RAP3DB
    volumes:
      - /home/ampersandadmin/database:/var/lib/mysql

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db