version: '2'

services:
  rap3:
    build: ./RAP3
    ports:
      - "80:80"
    links:
      - db

  db:
    image: mariadb:10.1
    env_file: db-settings.env

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db

